<center>
<img src="https://habrastorage.org/files/fd4/502/43d/fd450243dd604b81b9713213a247aa20.jpg">


## <center>  Exploratory data analysis with Pandas
<b><a href="https://www.kaggleusercontent.com/kf/37925458/eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..3Fqmrt469hUgHt2dyF-x2w.3YaC8DbxOHqbjlFg37U4AAGDUYWn-o6fyuAsReVM-Q_j0NyVKe8PTGS7OMvbm8JWX0DTLmG2guMmRCA4ZgoUT_MqhwOC8in_311e8HPXU8Upk_w86yEw-gTkxTF00ZfqlvMdYBapI6d3xhUn4VQNJj1i8A_niasOxFDF-lUehUPYa_rJZWEPujhFJmm8jhK0rU2cT9zOjBBhGJL9PE8WYni4I8vJR8hsiO2WMFVeBWxNXhnG0ansiLMrGzab4cZV6dANBVUxvEBW1dmKvvrIKBHgcC8wA0PmoHgrn2O9ZgnX8QbfILbRIxb1AZ1yMA8mRKeMtZa5iBMmB_OR4hKvyBlabJ_WPzV_1WPT4XzPWKKgxnyj81ME6jnBbPFuWRyo85_nf1IQ7J9Fd-5TVr2ES6h4CdlsBqgelNUFARzMdU83nhMO5tLBFx0_ggPwbGyiAgHr5UK4UQNVl-YyZwHU7fGulbwlF2RenqwWyl6jffabG4npXWP3UUXwZ6_CiZUY371l9lor8c-Sg2GcdolNE1uH9P4IC3D5Ag9Z5PS9waZpOHpz8h86fnCNuv0-o4k10Xdr40Iss3mYRy10EV6N_-YI1pZDzgdGf4wH_TJPqGQVAdKdcrAy5v0QEl4YUkK1SlQows6tsvP0y5bPjgoKpF2LLxkktAyD-SeuJE6My0jB20a59fnyG3z5Vi65jioI.h1idqzlymi43mlASj4jxsQ/mlcourse.ai">mlcourse.ai</a></b>
Open Machine Learning Course

Unique values of all features (for more information, please see the links above):
- `age`: continuous.
- `workclass`: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- `fnlwgt`: continuous.
- `education`: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- `education-num`: continuous.
- `marital-status`: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- `occupation`: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- `relationship`: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- `race`: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- `sex`: Female, Male.
- `capital-gain`: continuous.
- `capital-loss`: continuous.
- `hours-per-week`: continuous.
- `native-country`: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- `salary`: >50K,<=50K

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../input/adult.data.csv')
data.head()

In [3]:
data.columns=data.columns.str.lower().str.replace('-','_')

In [4]:
data.columns

**1. How many men and women (*sex* feature) are represented in this dataset?**

In [5]:
data['sex'].value_counts()

In [6]:
data['sex'].value_counts(normalize=True)

**2. What is the average age (*age* feature) of women?**

In [7]:
data[data['sex']=='Female']['age'].mean()

**3. What is the percentage of German citizens (*native-country* feature)?**

In [120]:
data['native_country'].value_counts(normalize=True)*100

In [146]:
(data['native_country']=='Germany').sum()/len(data)*100

**4-5. What are the mean and standard deviation of age for those who earn more than 50K per year (*salary* feature) and those who earn less than 50K per year? **

In [108]:
data.groupby(['salary'])['age'].agg([np.mean,np.std])

**6. Is it true that people who earn more than 50K have at least high school education? (*education â€“ Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* or *Doctorate* feature)**

In [10]:
pd.crosstab(data['salary'],data['education'])

**7. Display age statistics for each race (*race* feature) and each gender (*sex* feature). Use *groupby()* and *describe()*. Find the maximum age of men of *Amer-Indian-Eskimo* race.**

In [68]:
columns_to_show = ["age"]
data.groupby(['race','sex'])[columns_to_show].describe()

In [136]:
columns_to_show = ["age"]
data.groupby(['sex','race'])[columns_to_show].describe()

<H3>How it works</H3>
1. list race </p>
2. divide race by sex</p>
3. show age stats</p>

**8. What is the proportion of those who earn a lot (>50K) greater: married or single men (*marital-status* feature)? Consider as married those who have a *marital-status* starting with *Married* (Married-civ-spouse, Married-spouse-absent or Married-AF-spouse), the rest are considered bachelors.**

In [157]:
married_list=['Married-civ-spouse', 'Married-spouse-absent', 'Married-AF-spouse']
df_men_married_lot=data[(data['marital_status'].isin(married_list)) & (data['sex']=='Male')&(data['salary']=='>50K')]

In [167]:
df_men_married_lot.head()

**9. What is the maximum number of hours a person works per week (*hours-per-week* feature)? How many people work such a number of hours, and what is the percentage of those who earn a lot (>50K) among them?**

In [165]:
data['hours_per_week'].max()

In [163]:
df_max_hour_per_week=data[data['hours_per_week']==data['hours_per_week'].max()]

In [164]:
df_max_hour_per_week.groupby('salary')['hours_per_week'].count()/len(df_max_hour_per_week)

**10. Count the average time of work (*hours-per-week*) for those who earn a little and a lot (*salary*) for each country (*native-country*). What will these be for Japan?**

In [82]:
data[data['native_country']=='Japan'].groupby(['native_country','salary'])['hours_per_week'].mean()

<H3>Steps</h3>
1. Define the dataframe --->   data[data['native_country']=='Japan']  </p>
2. Apply groupby